### ISSUE TITLE
No module named 'users'

### ISSUE THREAD

**Issue by PhysicistSouravDas** [PhysicistSouravDas/dj-gravatar#2]
**Describe the bug**
Error while using `dj-gravatar` (No module named 'users')

**To Reproduce**

- `pip install Django==3.2`
- `pip install dj-gravatar==0.0.1`
- `python manage.py runserver`

```bash
Watching for file changes with StatReloader
Performing system checks...

Traceback (most recent call last):
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\backends\django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\dj_gravatar\templatetags\gravatar.py", line 3, in <module>
    from  users.settings import configure_default_settings
ModuleNotFoundError: No module named 'users'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\core\management\commands\runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\core\management\commands\runserver.py", line 96, in handle
    self.run(**options)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\core\management\commands\runserver.py", line 103, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\utils\autoreload.py", line 638, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\utils\autoreload.py", line 623, in start_django
    reloader.run(django_main_thread)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\utils\autoreload.py", line 328, in run
    autoreload_started.send(sender=self)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\dispatch\dispatcher.py", line 182, in send
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\backends\django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\dj_gravatar\templatetags\gravatar.py", line 3, in <module>
    from  users.settings import configure_default_settings
ModuleNotFoundError: No module named 'users'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\sourav das\appdata\local\programs\python\python37-32\Lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\sourav das\appdata\local\programs\python\python37-32\Lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\core\management\base.py", line 423, in check
    databases=databases,
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\contrib\admin\checks.py", line 78, in check_dependencies
    for engine in engines.all():
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\backends\django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\backends\django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\backends\django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\backends\django.py", line 126, in get_package_libraries
    ) from e
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'dj_gravatar.templatetags.gravatar': No module named 'users'

    for receiver in self._live_receivers(sender)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\dispatch\dispatcher.py", line 182, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\autoreload.py", line 44, in watch_for_template_changes
    for directory in get_template_directories():
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\autoreload.py", line 17, in get_template_directories
    for backend in engines.all():
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\backends\django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\backends\django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\backends\django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "C:\Dev\Django projects\testing django dj-gravatar\.venv\lib\site-packages\django\template\backends\django.py", line 126, in get_package_libraries
    ) from e
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'dj_gravatar.templatetags.gravatar': No module named 'users'
```

**Comment by PhysicistSouravDas** [comment]
Fixed #1 and this issue with the following commits:
* 9343d48ef5fe5f3eb118ac33d8837771003bbde2
* a25f1cb3323cdf2aab78b4e3e17bc592620bb17a
Version 0.0.2 will be released since some major bugs have been fixed.
